version: "3.3"
networks:
   gamein:
     external: true
     
services:
  market:
    build: .
    container_name: market
    restart: always
    ports:
      - 8080:8080
    networks:
      - gamein
    environment:
      - spring.datasource.url=jdbc:postgresql://pgsql/gamein
      - spring.datasource.username=gamein
      - spring.datasource.password=gamein123
