version: "3.3"
networks:
   gamein:
     external: true
     
services:
  market:
    image: registry.dariasystem.com/gamein/market:dev
    container_name: market
    restart: always
    ports:
      - 8080:8081
    networks:
      - gamein
    environment:
      - spring.datasource.url=jdbc:postgresql://192.168.0.223/gamein-2022-new
      - spring.datasource.username=gamein
      - spring.datasource.password=gamein123
      - auth.url=https://api-gamein.dariahamrah.ir/dashboard/auth/info
      - live.data.url=http://192.168.0.222:8083/websocket/api/notify
      
  market-1:
    image: registry.dariasystem.com/gamein/market:dev
    container_name: market-1
    restart: always
    ports:
      - 9080:8080
    networks:
      - gamein
    environment:
      - spring.datasource.url=jdbc:postgresql://192.168.0.223/gamein-2022-new
      - spring.datasource.username=gamein
      - spring.datasource.password=gamein123
      - auth.url=https://api-gamein.dariahamrah.ir/dashboard/auth/info
      - live.data.url=http://192.168.0.222:8083/websocket/api/notify
 
