name: build market

on:
  push:
    branches: [ "master" ]

jobs:
  build-market:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - run: |
              ls -lah
              docker rm -f market      
              docker-compose up --build -d
              docker-compose ps
