name: build market

on:
  push:
    branches: [ "master" ]

jobs:


#  check-code:
#    runs-on: [self-hosted, linux]
#    steps:
#      - uses: actions/checkout@master
#      - run: |
#             export PATH=$PATH:/opt/gradle/gradle-8.1.1/bin
#             echo $PATH
#             gradle -v
#             gradle  --stacktrace sonar \
#                -Dsonar.projectKey=market \
#                -Dsonar.projectName='market' \
#                -Dsonar.host.url=http://192.168.0.202:9000 \
#                -Dsonar.token=sqp_80250f384a53857804d2fd15fdbe6da21e948c66
             
             
             
  build-market:
#    needs: check-code
    runs-on: [app-3]
    steps:
      - uses: actions/checkout@master
      - run: |
              docker login   -u daria -p 7HlUyiSD  https://registry.dariasystem.com
              docker build -t registry.dariasystem.com/gamein/market:dev .
              docker push registry.dariasystem.com/gamein/market:dev
              
              
              
  deploy-market:
    needs: build-market
    runs-on: [app]
    steps:
      - uses: actions/checkout@master
      - run: |
              docker login   -u daria -p 7HlUyiSD  https://registry.dariasystem.com
              docker pull registry.dariasystem.com/gamein/market:dev
              docker rm -f market      
              docker-compose up  -d market
              sleep 10
              docker-compose ps
              
              
              
  deploy-market-1:
    needs: build-market
    runs-on: [app-X]
    steps:
      - uses: actions/checkout@master
      - run: |
              docker login   -u daria -p 7HlUyiSD  https://registry.dariasystem.com
              docker pull registry.dariasystem.com/gamein/market:dev
              docker rm -f market-1
              docker compose up  -d market-1
              docker compose ps


