name: build market

on:
  push:
    branches: [ "master" ]

jobs:
  build-market:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - run: |
              whoami
              docker ps
              ls -lah 
