name: build market

on:
  push:
    branches: [ "master" ]

jobs:
  build-market:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - run: |
              ls -lah
              docker build -t market:dev .
              docker rm -f market      
              docker-compose up  -d market
              sleep 20
              docker rm -f market-1
              docker-compose up  -d market-1
              docker-compose ps

